# Generated by Django 5.2.3 on 2025-07-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='none title', max_length=200),
            preserve_default=False,
        ),
    ]
