# Generated by Django 5.2.3 on 2025-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Yapılacak'), ('in-progress', 'Devam Ediyor'), ('done', 'Tamamlandı')], default='todo', max_length=20),
        ),
    ]
